[alias]
rr = "run --release"

[target.riscv32imc-unknown-none-elf]
runner = "espflash flash --monitor --chip esp32c3"

[env]

[build]
rustflags = [
  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  # NOTE: May negatively impact performance of produced code
  "-C", "force-frame-pointers",
]

target = "riscv32imc-unknown-none-elf"

[unstable]
build-std = ["core"]

# [target.riscv32imc-unknown-none-elf]
# runner = "espflash flash --port COM4 --monitor"

# [build]
# rustflags = [
# 	"-C", "link-arg=-Tlinkall.x",
# 	# Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
# 	# NOTE: May negatively impact performance of produced code
# 	"-C", "force-frame-pointers",

# 	# comment the cfgs below if you do _not_ wish to emulate atomics.
# 	# enable the atomic codegen option for RISCV
# 	"-C", "target-feature=+a",
# ]

# target = "riscv32imc-unknown-none-elf"

# [unstable]
# build-std = ["core"]
